### PR TITLE
Member logging hopefully, not tested too lazy

### PR DESCRIPTION
**Pull request by Aresiel**

### CODE REVIEW

**Review by ScourgeTheHedgehog — CHANGES_REQUESTED** [review]
This should be configurable by database, and it has to be in its own file.

**Comment by Aresiel** [comment]
Nothing else is in its own file

**Comment by ScourgeTheHedgehog** [comment]
> Nothing else is in its own file

Commands are.
Stuff that isn't in it's own file isn't supposed to be.

Nevertheless this is an *event* if you get what i mean, I'd like commands and events in their own folder/file.

**Comment by Aresiel** [comment]
And how do you make modules with events in your system?

**Comment by Aresiel** [comment]
And the onready event sure isn't

**Comment by ScourgeTheHedgehog** [comment]
> And the onready event sure isn't

This isn't relevant.

> And how do you make modules with events in your system?

I'd say check the command handler to see if it can do that, otherwise wait till i find out how to do that or add that possibility yourself.

**Pull request closed without merging**
